server:
  port: 9085
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    driverClassName: org.postgresql.Driver
    username: postgres
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL81Dialect

